CREATE DATABASE IF NOT EXISTS student_ms;
USE student_ms;

CREATE TABLE IF NOT EXISTS admin (
    AdminID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO admin (Name, Email, Password) VALUES 
('System Admin', 'admin@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'); -- password is 'admin123'

CREATE TABLE IF NOT EXISTS student (
    StudentID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    ProfilePicture VARCHAR(255) DEFAULT NULL,
    DateOfBirth DATE,
    ContactNo VARCHAR(20),
    Address TEXT,
    ClassGrade VARCHAR(20),
    AcademicYear VARCHAR(20),
    Section VARCHAR(5) DEFAULT NULL,
    RollNumber VARCHAR(20) DEFAULT NULL,
    AdmissionDate DATE DEFAULT NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    ApprovedBy INT DEFAULT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ApprovedBy) REFERENCES admin(AdminID) ON DELETE SET NULL
);

